#!/usr/bin/env node
import { readFile, writeFile } from 'node:fs/promises';
import { execFileSync } from 'node:child_process';
import { resolve } from 'node:path';

const args = process.argv.slice(2);
const arg = name => { const i = args.indexOf(name); return i >= 0 ? args[i + 1] : null; };
const target = resolve('src/version.js');
let build = arg('--build') || process.env.FD_BUILD || null;
let version = arg('--version') || process.env.FD_VERSION || null;
let protocol = arg('--protocol') || process.env.FD_PROTOCOL_VERSION || '1.0.0';

if (!build || !version) {
  try {
    const tag = execFileSync('git', ['describe', '--tags', '--exact-match'], { encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] }).trim();
    const semver = tag.match(/v?(\d+\.\d+\.\d+)/)?.[1];
    const tagBuild = tag.match(/(?:build|b)[-_.]?(\d+)/i)?.[1];
    version ||= semver || null;
    build ||= tagBuild || null;
  } catch { /* explicit args/env or existing file are used below */ }
}

if (!build || !version) {
  const current = await readFile(target, 'utf8').catch(() => '');
  build ||= current.match(/BUILD\s*=\s*(\d+)/)?.[1] || null;
  version ||= current.match(/VERSION\s*=\s*['"]([^'"]+)/)?.[1] || null;
}

if (!/^\d+$/.test(String(build || '')) || Number(build) < 1) throw new Error(`invalid build: ${build}`);
if (!/^\d+\.\d+\.\d+(?:[-+][0-9A-Za-z.-]+)?$/.test(String(version || ''))) throw new Error(`invalid semver: ${version}`);
if (!/^\d+\.\d+\.\d+(?:[-+][0-9A-Za-z.-]+)?$/.test(String(protocol || ''))) throw new Error(`invalid protocol semver: ${protocol}`);

const text = `// Generated by tools/write-version.mjs. Do not edit build identity elsewhere.\nexport const BUILD = ${Number(build)};\nexport const VERSION = '${version}';\nexport const PROTOCOL_VERSION = '${protocol}';\n\nexport default Object.freeze({ BUILD, VERSION, PROTOCOL_VERSION });\n`;
await writeFile(target, text, 'utf8');
console.log(`version: build=${build} version=${version} protocol=${protocol}`);
