// Generated by tools/write-version.mjs. Do not edit build identity elsewhere.
export const BUILD = 213;
export const VERSION = '16.9.7';
export const PROTOCOL_VERSION = '1.0.0';

export default Object.freeze({ BUILD, VERSION, PROTOCOL_VERSION });
